-- CE-12 (S074-S077) — initial schema for vehicle-accounting-service.
-- Additive-only; folder-per-migration Prisma format, generated by
-- `prisma migrate dev --create-only` and reviewed by hand (matches
-- services/tax-service/prisma/migrations's committed-migration convention).
-- See services/vehicle-accounting-service/prisma/schema.prisma for
-- field-level rationale.

-- CreateTable
CREATE TABLE "vehicle_unit" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "store_id" TEXT NOT NULL,
    "vin" TEXT NOT NULL,
    "stock_number" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'NEW',
    "acquisition_type" TEXT NOT NULL,
    "book_value" DECIMAL(15,2) NOT NULL DEFAULT 0,
    "cumulative_write_down" DECIMAL(15,2) NOT NULL DEFAULT 0,
    "disposed_at" TIMESTAMP(3),
    "disposal_type" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "vehicle_unit_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vehicle_cost_component" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "unit_id" TEXT NOT NULL,
    "component_type" TEXT NOT NULL,
    "amount" DECIMAL(15,2) NOT NULL,
    "description" TEXT,
    "source_event_id" TEXT NOT NULL,
    "source_event_type" TEXT NOT NULL,
    "posting_execution_id" TEXT,
    "journal_entry_id" TEXT,
    "journal_number" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "vehicle_cost_component_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vehicle_stock_in_event" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "unit_id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "correlation_id" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "posting_execution_id" TEXT,
    "journal_entry_id" TEXT,
    "journal_number" TEXT,
    "failure_reason" TEXT,
    "request_payload" JSONB NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "vehicle_stock_in_event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vehicle_recon_cost_event" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "unit_id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "ro_number" TEXT NOT NULL,
    "amount" DECIMAL(15,2) NOT NULL,
    "status" TEXT NOT NULL,
    "posting_execution_id" TEXT,
    "journal_entry_id" TEXT,
    "journal_number" TEXT,
    "failure_reason" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "vehicle_recon_cost_event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vehicle_cost_component_event" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "unit_id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "component_type" TEXT NOT NULL,
    "amount" DECIMAL(15,2) NOT NULL,
    "pack_role" TEXT,
    "status" TEXT NOT NULL,
    "posting_execution_id" TEXT,
    "journal_entry_id" TEXT,
    "journal_number" TEXT,
    "failure_reason" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "vehicle_cost_component_event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vehicle_pack_policy_config" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "pack_role" TEXT NOT NULL,
    "pack_basis" TEXT NOT NULL,
    "pack_amount" DECIMAL(15,2),
    "pack_percent_bp" INTEGER,
    "updated_by" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "vehicle_pack_policy_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "demo_reclass" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "unit_id" TEXT NOT NULL,
    "event_id" TEXT NOT NULL,
    "from_status" TEXT NOT NULL,
    "to_status" TEXT NOT NULL,
    "unit_value" DECIMAL(15,2) NOT NULL,
    "status" TEXT NOT NULL,
    "posting_execution_id" TEXT,
    "journal_entry_id" TEXT,
    "journal_number" TEXT,
    "failure_reason" TEXT,
    "actor" TEXT NOT NULL,
    "idempotency_key" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "demo_reclass_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "demo_depreciation_basis_config" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "percent_per_period_bp" INTEGER NOT NULL,
    "period_length_days" INTEGER NOT NULL DEFAULT 30,
    "updated_by" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "demo_depreciation_basis_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "demo_value_adjustment" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "unit_id" TEXT NOT NULL,
    "basis_config_id" TEXT,
    "proposed_amount" DECIMAL(15,2) NOT NULL,
    "computed_at" TIMESTAMP(3) NOT NULL,
    "computed_by" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING_PREVIEW',
    "approved_amount" DECIMAL(15,2),
    "approved_by" TEXT,
    "approved_at" TIMESTAMP(3),
    "rejected_reason" TEXT,
    "event_id" TEXT,
    "posting_execution_id" TEXT,
    "journal_entry_id" TEXT,
    "journal_number" TEXT,
    "failure_reason" TEXT,
    "reversal_journal_entry_id" TEXT,
    "reversed_at" TIMESTAMP(3),
    "reversed_by" TEXT,
    "reversal_reason" TEXT,
    "idempotency_key" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "demo_value_adjustment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lcnrv_threshold_config" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "max_write_down_amount" DECIMAL(15,2) NOT NULL,
    "updated_by" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lcnrv_threshold_config_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lcnrv_market_evidence" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "unit_id" TEXT NOT NULL,
    "market_value" DECIMAL(15,2) NOT NULL,
    "source" TEXT NOT NULL,
    "reference" TEXT,
    "note" TEXT,
    "entered_by" TEXT NOT NULL,
    "entered_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lcnrv_market_evidence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lcnrv_write_down" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "unit_id" TEXT NOT NULL,
    "evidence_id" TEXT NOT NULL,
    "book_value_before" DECIMAL(15,2) NOT NULL,
    "market_value" DECIMAL(15,2) NOT NULL,
    "write_down_amount" DECIMAL(15,2) NOT NULL,
    "reason" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "refusal_reason" TEXT,
    "event_id" TEXT,
    "posting_execution_id" TEXT,
    "journal_entry_id" TEXT,
    "journal_number" TEXT,
    "failure_reason" TEXT,
    "actor" TEXT NOT NULL,
    "idempotency_key" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lcnrv_write_down_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dealer_trade" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "store_id" TEXT NOT NULL,
    "trade_number" TEXT NOT NULL,
    "direction" TEXT NOT NULL,
    "counterparty_dealer" TEXT NOT NULL,
    "unit_id" TEXT,
    "agreed_value" DECIMAL(15,2) NOT NULL,
    "book_value_at_trade" DECIMAL(15,2),
    "gain_loss_amount" DECIMAL(15,2),
    "gain_loss_direction" TEXT,
    "status" TEXT NOT NULL DEFAULT 'OPEN',
    "event_id" TEXT,
    "posting_execution_id" TEXT,
    "journal_entry_id" TEXT,
    "journal_number" TEXT,
    "failure_reason" TEXT,
    "actor" TEXT NOT NULL,
    "idempotency_key" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "dealer_trade_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dealer_trade_settlement" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "trade_id" TEXT NOT NULL,
    "netted_amount" DECIMAL(15,2) NOT NULL,
    "cash_difference_amount" DECIMAL(15,2) NOT NULL DEFAULT 0,
    "cash_difference_pending" BOOLEAN NOT NULL DEFAULT false,
    "status" TEXT NOT NULL,
    "event_id" TEXT,
    "posting_execution_id" TEXT,
    "journal_entry_id" TEXT,
    "journal_number" TEXT,
    "failure_reason" TEXT,
    "actor" TEXT NOT NULL,
    "idempotency_key" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "dealer_trade_settlement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "audit_outbox" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "doc_type" TEXT NOT NULL,
    "doc_id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "before" JSONB,
    "after" JSONB,
    "actor" TEXT NOT NULL,
    "published_at" TIMESTAMP(3),
    "retry_count" INTEGER NOT NULL DEFAULT 0,
    "last_error" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_outbox_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "vehicle_unit_tenant_id_vin_idx" ON "vehicle_unit"("tenant_id", "vin");

-- CreateIndex
CREATE INDEX "vehicle_unit_tenant_id_entity_id_status_idx" ON "vehicle_unit"("tenant_id", "entity_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "vehicle_unit_tenant_id_stock_number_key" ON "vehicle_unit"("tenant_id", "stock_number");

-- CreateIndex
CREATE INDEX "vehicle_cost_component_tenant_id_unit_id_idx" ON "vehicle_cost_component"("tenant_id", "unit_id");

-- CreateIndex
CREATE UNIQUE INDEX "vehicle_cost_component_tenant_id_source_event_id_key" ON "vehicle_cost_component"("tenant_id", "source_event_id");

-- CreateIndex
CREATE INDEX "vehicle_stock_in_event_tenant_id_unit_id_idx" ON "vehicle_stock_in_event"("tenant_id", "unit_id");

-- CreateIndex
CREATE UNIQUE INDEX "vehicle_stock_in_event_tenant_id_event_id_key" ON "vehicle_stock_in_event"("tenant_id", "event_id");

-- CreateIndex
CREATE INDEX "vehicle_recon_cost_event_tenant_id_unit_id_idx" ON "vehicle_recon_cost_event"("tenant_id", "unit_id");

-- CreateIndex
CREATE UNIQUE INDEX "vehicle_recon_cost_event_tenant_id_event_id_key" ON "vehicle_recon_cost_event"("tenant_id", "event_id");

-- CreateIndex
CREATE INDEX "vehicle_cost_component_event_tenant_id_unit_id_idx" ON "vehicle_cost_component_event"("tenant_id", "unit_id");

-- CreateIndex
CREATE UNIQUE INDEX "vehicle_cost_component_event_tenant_id_event_id_key" ON "vehicle_cost_component_event"("tenant_id", "event_id");

-- CreateIndex
CREATE UNIQUE INDEX "vehicle_pack_policy_config_tenant_id_entity_id_key" ON "vehicle_pack_policy_config"("tenant_id", "entity_id");

-- CreateIndex
CREATE INDEX "demo_reclass_tenant_id_unit_id_idx" ON "demo_reclass"("tenant_id", "unit_id");

-- CreateIndex
CREATE UNIQUE INDEX "demo_reclass_tenant_id_event_id_key" ON "demo_reclass"("tenant_id", "event_id");

-- CreateIndex
CREATE UNIQUE INDEX "demo_reclass_tenant_id_idempotency_key_key" ON "demo_reclass"("tenant_id", "idempotency_key");

-- CreateIndex
CREATE UNIQUE INDEX "demo_depreciation_basis_config_tenant_id_entity_id_key" ON "demo_depreciation_basis_config"("tenant_id", "entity_id");

-- CreateIndex
CREATE INDEX "demo_value_adjustment_tenant_id_unit_id_idx" ON "demo_value_adjustment"("tenant_id", "unit_id");

-- CreateIndex
CREATE INDEX "demo_value_adjustment_tenant_id_status_idx" ON "demo_value_adjustment"("tenant_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "demo_value_adjustment_tenant_id_idempotency_key_key" ON "demo_value_adjustment"("tenant_id", "idempotency_key");

-- CreateIndex
CREATE UNIQUE INDEX "lcnrv_threshold_config_tenant_id_entity_id_key" ON "lcnrv_threshold_config"("tenant_id", "entity_id");

-- CreateIndex
CREATE INDEX "lcnrv_market_evidence_tenant_id_unit_id_idx" ON "lcnrv_market_evidence"("tenant_id", "unit_id");

-- CreateIndex
CREATE INDEX "lcnrv_write_down_tenant_id_unit_id_idx" ON "lcnrv_write_down"("tenant_id", "unit_id");

-- CreateIndex
CREATE UNIQUE INDEX "lcnrv_write_down_tenant_id_idempotency_key_key" ON "lcnrv_write_down"("tenant_id", "idempotency_key");

-- CreateIndex
CREATE INDEX "dealer_trade_tenant_id_unit_id_idx" ON "dealer_trade"("tenant_id", "unit_id");

-- CreateIndex
CREATE UNIQUE INDEX "dealer_trade_tenant_id_trade_number_direction_key" ON "dealer_trade"("tenant_id", "trade_number", "direction");

-- CreateIndex
CREATE UNIQUE INDEX "dealer_trade_tenant_id_idempotency_key_key" ON "dealer_trade"("tenant_id", "idempotency_key");

-- CreateIndex
CREATE UNIQUE INDEX "dealer_trade_settlement_trade_id_key" ON "dealer_trade_settlement"("trade_id");

-- CreateIndex
CREATE UNIQUE INDEX "dealer_trade_settlement_tenant_id_idempotency_key_key" ON "dealer_trade_settlement"("tenant_id", "idempotency_key");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "audit_outbox_published_at_retry_count_idx" ON "audit_outbox"("published_at", "retry_count");

-- AddForeignKey
ALTER TABLE "vehicle_cost_component" ADD CONSTRAINT "vehicle_cost_component_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "vehicle_unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "vehicle_stock_in_event" ADD CONSTRAINT "vehicle_stock_in_event_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "vehicle_unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "demo_reclass" ADD CONSTRAINT "demo_reclass_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "vehicle_unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "demo_value_adjustment" ADD CONSTRAINT "demo_value_adjustment_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "vehicle_unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lcnrv_market_evidence" ADD CONSTRAINT "lcnrv_market_evidence_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "vehicle_unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lcnrv_write_down" ADD CONSTRAINT "lcnrv_write_down_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "vehicle_unit"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dealer_trade_settlement" ADD CONSTRAINT "dealer_trade_settlement_trade_id_fkey" FOREIGN KEY ("trade_id") REFERENCES "dealer_trade"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
