import {
  CanonicalGLAccount,
  GLAccountType,
  StandardChartOfAccounts,
} from '@amacc/shared-kernel';

// Standard automotive dealership chart of accounts
// Pre-built at platform level with OEM Financial Statement mappings
const STANDARD_ACCOUNTS: CanonicalGLAccount[] = [
  // Assets
  { amaccCode: 'AMACC_GL_100', standardName: 'Cash in Bank', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'CASH', oemMappings: { GM: { accountCode: '202', lineNumber: 1, pageNumber: 1, required: true, fsCategory: 'CASH' }, FORD: { accountCode: 'CHK', lineNumber: 1, pageNumber: 1, required: true, fsCategory: 'CASH' } }, allowedTransactionTypes: ['CASH_RECEIPT', 'JOURNAL_ENTRY', 'ADJUSTMENT'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_101', standardName: 'Cash in Bank - Payroll', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'CASH', oemMappings: { GM: { accountCode: '203', lineNumber: 2, pageNumber: 1, required: false, fsCategory: 'CASH' } }, allowedTransactionTypes: ['PAYROLL', 'JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_110', standardName: 'Accounts Receivable - Trade', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'RECEIVABLES', oemMappings: { GM: { accountCode: '210', lineNumber: 3, pageNumber: 1, required: true, fsCategory: 'RECEIVABLES' }, FORD: { accountCode: 'AR', lineNumber: 2, pageNumber: 1, required: true, fsCategory: 'RECEIVABLES' } }, allowedTransactionTypes: ['VEHICLE_SALE', 'PARTS_SALE', 'SERVICE_LABOR', 'CASH_RECEIPT'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_111', standardName: 'Accounts Receivable - Factory', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'RECEIVABLES', oemMappings: { GM: { accountCode: '211', lineNumber: 4, pageNumber: 1, required: true, fsCategory: 'RECEIVABLES' } }, allowedTransactionTypes: ['WARRANTY_CLAIM', 'JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_120', standardName: 'New Vehicle Inventory', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'INVENTORY', oemMappings: { GM: { accountCode: '230', lineNumber: 8, pageNumber: 1, required: true, fsCategory: 'INVENTORY' }, FORD: { accountCode: 'NVI', lineNumber: 6, pageNumber: 1, required: true, fsCategory: 'INVENTORY' } }, allowedTransactionTypes: ['VEHICLE_SALE', 'JOURNAL_ENTRY', 'ADJUSTMENT'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_121', standardName: 'Used Vehicle Inventory', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'INVENTORY', oemMappings: { GM: { accountCode: '231', lineNumber: 9, pageNumber: 1, required: true, fsCategory: 'INVENTORY' } }, allowedTransactionTypes: ['VEHICLE_SALE', 'JOURNAL_ENTRY', 'ADJUSTMENT'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_130', standardName: 'Parts Inventory', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'INVENTORY', oemMappings: { GM: { accountCode: '240', lineNumber: 12, pageNumber: 1, required: true, fsCategory: 'INVENTORY' } }, allowedTransactionTypes: ['PARTS_SALE', 'JOURNAL_ENTRY', 'ADJUSTMENT'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_150', standardName: 'Land', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'FIXED_ASSETS', oemMappings: { GM: { accountCode: '260', lineNumber: 18, pageNumber: 1, required: false, fsCategory: 'FIXED_ASSETS' } }, allowedTransactionTypes: ['JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_151', standardName: 'Buildings', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'FIXED_ASSETS', oemMappings: { GM: { accountCode: '261', lineNumber: 19, pageNumber: 1, required: false, fsCategory: 'FIXED_ASSETS' } }, allowedTransactionTypes: ['JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_152', standardName: 'Furniture & Equipment', accountType: GLAccountType.ASSET, normalBalance: 'DEBIT', fsCategory: 'FIXED_ASSETS', oemMappings: { GM: { accountCode: '263', lineNumber: 21, pageNumber: 1, required: false, fsCategory: 'FIXED_ASSETS' } }, allowedTransactionTypes: ['JOURNAL_ENTRY'], isSystemAccount: true },

  // Liabilities
  { amaccCode: 'AMACC_GL_200', standardName: 'Accounts Payable - Trade', accountType: GLAccountType.LIABILITY, normalBalance: 'CREDIT', fsCategory: 'CURRENT_LIABILITIES', oemMappings: { GM: { accountCode: '301', lineNumber: 1, pageNumber: 2, required: true, fsCategory: 'CURRENT_LIABILITIES' }, FORD: { accountCode: 'AP', lineNumber: 1, pageNumber: 2, required: true, fsCategory: 'CURRENT_LIABILITIES' } }, allowedTransactionTypes: ['ACCOUNTS_PAYABLE', 'JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_210', standardName: 'New Vehicle Floor Plan', accountType: GLAccountType.LIABILITY, normalBalance: 'CREDIT', fsCategory: 'CURRENT_LIABILITIES', oemMappings: { GM: { accountCode: '310', lineNumber: 3, pageNumber: 2, required: true, fsCategory: 'CURRENT_LIABILITIES' } }, allowedTransactionTypes: ['VEHICLE_SALE', 'JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_211', standardName: 'Used Vehicle Floor Plan', accountType: GLAccountType.LIABILITY, normalBalance: 'CREDIT', fsCategory: 'CURRENT_LIABILITIES', oemMappings: { GM: { accountCode: '311', lineNumber: 4, pageNumber: 2, required: true, fsCategory: 'CURRENT_LIABILITIES' } }, allowedTransactionTypes: ['VEHICLE_SALE', 'JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_220', standardName: 'Accrued Payroll', accountType: GLAccountType.LIABILITY, normalBalance: 'CREDIT', fsCategory: 'CURRENT_LIABILITIES', oemMappings: { GM: { accountCode: '320', lineNumber: 7, pageNumber: 2, required: true, fsCategory: 'CURRENT_LIABILITIES' } }, allowedTransactionTypes: ['PAYROLL', 'JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_250', standardName: 'Long-Term Debt', accountType: GLAccountType.LIABILITY, normalBalance: 'CREDIT', fsCategory: 'LONG_TERM_LIABILITIES', oemMappings: { GM: { accountCode: '350', lineNumber: 15, pageNumber: 2, required: false, fsCategory: 'LONG_TERM_LIABILITIES' } }, allowedTransactionTypes: ['JOURNAL_ENTRY'], isSystemAccount: true },

  // Equity
  { amaccCode: 'AMACC_GL_300', standardName: 'Owner Equity', accountType: GLAccountType.EQUITY, normalBalance: 'CREDIT', fsCategory: 'NET_WORTH', oemMappings: { GM: { accountCode: '401', lineNumber: 1, pageNumber: 3, required: true, fsCategory: 'NET_WORTH' } }, allowedTransactionTypes: ['JOURNAL_ENTRY', 'YEAR_END'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_310', standardName: 'Retained Earnings', accountType: GLAccountType.EQUITY, normalBalance: 'CREDIT', fsCategory: 'NET_WORTH', oemMappings: { GM: { accountCode: '410', lineNumber: 3, pageNumber: 3, required: true, fsCategory: 'NET_WORTH' } }, allowedTransactionTypes: ['YEAR_END'], isSystemAccount: true },

  // Revenue
  { amaccCode: 'AMACC_GL_400', standardName: 'New Vehicle Sales', accountType: GLAccountType.REVENUE, normalBalance: 'CREDIT', fsCategory: 'REVENUE', oemMappings: { GM: { accountCode: '501', lineNumber: 1, pageNumber: 4, required: true, fsCategory: 'REVENUE' }, FORD: { accountCode: 'NVS', lineNumber: 1, pageNumber: 3, required: true, fsCategory: 'REVENUE' } }, allowedTransactionTypes: ['VEHICLE_SALE'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_401', standardName: 'Used Vehicle Sales - Retail', accountType: GLAccountType.REVENUE, normalBalance: 'CREDIT', fsCategory: 'REVENUE', oemMappings: { GM: { accountCode: '502', lineNumber: 2, pageNumber: 4, required: true, fsCategory: 'REVENUE' } }, allowedTransactionTypes: ['VEHICLE_SALE'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_410', standardName: 'Service Labor Sales', accountType: GLAccountType.REVENUE, normalBalance: 'CREDIT', fsCategory: 'REVENUE', oemMappings: { GM: { accountCode: '520', lineNumber: 8, pageNumber: 4, required: true, fsCategory: 'REVENUE' } }, allowedTransactionTypes: ['SERVICE_LABOR'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_420', standardName: 'Parts Sales', accountType: GLAccountType.REVENUE, normalBalance: 'CREDIT', fsCategory: 'REVENUE', oemMappings: { GM: { accountCode: '530', lineNumber: 12, pageNumber: 4, required: true, fsCategory: 'REVENUE' } }, allowedTransactionTypes: ['PARTS_SALE'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_430', standardName: 'F&I Income', accountType: GLAccountType.REVENUE, normalBalance: 'CREDIT', fsCategory: 'REVENUE', oemMappings: { GM: { accountCode: '540', lineNumber: 16, pageNumber: 4, required: true, fsCategory: 'REVENUE' } }, allowedTransactionTypes: ['VEHICLE_SALE'], isSystemAccount: true },

  // Cost of Sales
  { amaccCode: 'AMACC_GL_500', standardName: 'Cost of New Vehicles Sold', accountType: GLAccountType.COST_OF_SALES, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '601', lineNumber: 1, pageNumber: 5, required: true, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['VEHICLE_SALE'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_501', standardName: 'Cost of Used Vehicles Sold', accountType: GLAccountType.COST_OF_SALES, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '602', lineNumber: 2, pageNumber: 5, required: true, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['VEHICLE_SALE'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_510', standardName: 'Service Cost of Sales', accountType: GLAccountType.COST_OF_SALES, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '620', lineNumber: 8, pageNumber: 5, required: true, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['SERVICE_LABOR'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_520', standardName: 'Parts Cost of Sales', accountType: GLAccountType.COST_OF_SALES, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '630', lineNumber: 12, pageNumber: 5, required: true, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['PARTS_SALE'], isSystemAccount: true },

  // Operating Expenses
  { amaccCode: 'AMACC_GL_600', standardName: 'Salaries & Wages', accountType: GLAccountType.EXPENSE, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '701', lineNumber: 1, pageNumber: 6, required: true, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['PAYROLL'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_610', standardName: 'Commissions', accountType: GLAccountType.EXPENSE, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '710', lineNumber: 4, pageNumber: 6, required: true, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['PAYROLL'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_620', standardName: 'Advertising', accountType: GLAccountType.EXPENSE, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '720', lineNumber: 8, pageNumber: 6, required: true, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['ACCOUNTS_PAYABLE', 'JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_630', standardName: 'Rent & Occupancy', accountType: GLAccountType.EXPENSE, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '730', lineNumber: 12, pageNumber: 6, required: false, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_640', standardName: 'Insurance', accountType: GLAccountType.EXPENSE, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '740', lineNumber: 15, pageNumber: 6, required: false, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['JOURNAL_ENTRY'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_650', standardName: 'Depreciation', accountType: GLAccountType.EXPENSE, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '750', lineNumber: 18, pageNumber: 6, required: false, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['JOURNAL_ENTRY', 'ADJUSTMENT'], isSystemAccount: true },
  { amaccCode: 'AMACC_GL_660', standardName: 'Floor Plan Interest', accountType: GLAccountType.EXPENSE, normalBalance: 'DEBIT', fsCategory: 'EXPENSE', oemMappings: { GM: { accountCode: '760', lineNumber: 22, pageNumber: 6, required: true, fsCategory: 'EXPENSE' } }, allowedTransactionTypes: ['JOURNAL_ENTRY'], isSystemAccount: true },
];

export const STANDARD_COA: StandardChartOfAccounts = {
  version: '2026.1',
  effectiveDate: new Date('2026-01-01'),
  accounts: STANDARD_ACCOUNTS,
  oemCoverage: ['GM', 'FORD'],
};
