-- MOVED (defect fix): this file's content never actually applied via
-- `prisma migrate deploy`, because it lived directly in prisma/migrations/
-- instead of inside a timestamped migration subfolder that Prisma's deploy
-- tooling recognizes. Verified empirically: after applying every migration
-- Prisma DID recognize to a fresh dev database, `pg_trigger` showed zero
-- triggers on audit_logs. The real, deployable copy of this trigger now
-- lives at:
--
--   prisma/migrations/20260727000002_make_auditlog_immutable/migration.sql
--
-- This stray file is kept only so `git log` history for the original content
-- is not lost; it is not read by any tooling and must not be edited further.
